apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer # With this tiype we expose to the public
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
