apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer # With this tiype we expose to the public
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
